### PR TITLE
Daemonize kewatcher and log to syslog (daemon closes stdout and stderr)

### PR DESCRIPTION
**Pull request by benprew**

### CODE REVIEW

**Comment by benprew** [comment]
@kmullin These tests pass locally for me, I'm not familiar with TravisCI, it looks like the tests aren't completing?  Is there something I should look at?  Or, can you get Travis to re-run the build?

**Comment by kmullin** [comment]
So I would like to merge this in separately from the syslog addition, but due to forking a daemon, we will need to be more specific in when we start opening file descriptors.

Likely you've introduced syslog stuff to quickly get past the daemonizing closing stdout/err.

I'm not sure when I'll have time to test the daemonize changes independently from the syslog stuff, but I do like that feature.

Historically I've relied on the shell which can launch the daemon into background properly.

**Comment by benprew** [comment]
Ok, I can break out the changes, but I'll have to make some kind of logging change, right? (Since the current logging uses stdout/err and daemon closes those)  I could add a logfile option and log to that instead of syslog?

**Comment by kmullin** [comment]
Hmm its been so long since I've actually looked at this code, I totally thought I had a logfile option... appears I do not.

I suppose my default approach to this would be to use a logger gem, and have it instantiate after daemonizing so fd's are created correctly after the various forks.

IIRC, the use of Process.daemon is not supported in Ruby 1.8.7, which I'd like to still support, so something like this is needed:

``` ruby
        # stolen from Rack
        if RUBY_VERSION < "1.9"
          exit if fork
          Process.setsid
          exit if fork
          Dir.chdir(options[:working_dir])
          STDIN.reopen('/dev/null')
          STDOUT.reopen('/dev/null', 'a')
          STDERR.reopen('/dev/null', 'a')
        else
          Process.daemon(chdir=options[:working_dir])
        end
```

**Comment by benprew** [comment]
Those changes sound good, I'll update the pull request.

Thanks

**Pull request closed without merging**
